### ISSUE TITLE
[request] Tag needs :focus and maybe :active styles spec'd in Figma

### ISSUE THREAD

**Issue by WilliamKelley** [prenda-school/design-system#206]
WIP, just starting this so I don't forget about it.

Mui Chips establish the pattern that Tag uses. The whole Tag (Chip) is "focusable" but the delete icon is hoverable. So we can dupe the hover styling on focus, but the user is actually focused on the tag, so the tag needs focus styling spec'd.

My best guess was that it would be a darkened border color.

I did not guess what the `:active` styling would be.

**Comment by alecdanz** [comment]
Current designs account for a [focus state of the tag](https://www.figma.com/file/y6Ca8BdJtQEd3Of1saRieF/components?node-id=949%3A467&t=1UBeb8uOuxyDPt4p-1), closing issue.
