### ISSUE TITLE
[request] MenuItem needs `selected` styles separated

### ISSUE THREAD

**Issue by WilliamKelley** [prenda-school/design-system#209]
The "Menu" Figma page currently has specs for "Menu Item" and its variations.

The default, hover, focus, and disabled styles are all good.

But, what's currently the `:active` style is probably meant to be the "`selected`" style. 
  - `selected` indicates it's the (or a) current choice among other menu items
  - `:active` is a pseudo style applied when a user clicks / taps it -- having it being a drastically different color will produce a jarring flash

Both un-`selected` and `selected` should have styles for
  - default
  - hover
  - focus
  - active
  - disabled

cc: @ssbittle

**Comment by WilliamKelley** [comment]
You can see my best guesses through Chromatic in #210

**Comment by alecdanz** [comment]
Fixed with [menu item changes](https://www.figma.com/file/y6Ca8BdJtQEd3Of1saRieF/components?node-id=5062%3A9820).
