### ISSUE TITLE
[request] Add component specs for Link

### ISSUE THREAD

**Issue by WilliamKelley** [prenda-school/design-system#225]
Currently, different Typography variants are contained in the Typography figma file, and "Link" is also there. I think these can benefit from having a dedicated page and figma component spec'd in the Components figma file as well. 

For Typography, I have in mind that instead of designs containing lone "Text" instances, that designs instead use "Typography" component instances with dedicated variants for each style. One beneficial offshoot i'm hoping for is to protect against using two text styles in the same text box. Also against making a text box having artificially inflated height instead of hugging the text -- like it would in implementation. And finally to ease the mental flow of a developer, who's implementing a given design, coming across a dedicated Typography component with a named variant, like they would use in the code implementation, instead of a text box.

For Link, this is a much more practical request than Typography. We need the variants and pseudo-states spec'd out to design a complete component for Link.

cc: @ssbittle @alecdanz

**Comment by alecdanz** [comment]
I don't think that we're going to be able to get to a place where type is a component rather than a style on a text element. There is a pretty big mind-shift change that we would have to do and I don't think that we would have quite the control that is always needed when creating a design. 

I'd love to address some of those concerns with the team to make sure that they're designing with different text layers when possible. 

For a link, we do already have a button variant of a link - is this something that you think needs to be different?

**Comment by WilliamKelley** [comment]
> 
> For a link, we do already have a button variant of a link - is this something that you think needs to be different?

I'm not sure what you mean by this

**Comment by alecdanz** [comment]
For sure. Happy to talk more over a call. Maybe tomorrow if you're available?

**Comment by WilliamKelley** [comment]
Definitely! my google cal is open

**Comment by WilliamKelley** [comment]
Revised issue to just request component file spec for Link

**Comment by WilliamKelley** [comment]
@alecdanz @ssbittle Would be great to get a spec on this ASAP. This is an essential element probably being used by all consumers, but not with consistency. We also get Breadcrumbs practically free with this.

**Comment by alecdanz** [comment]
Hey, working on new styles right now. Went ahead and defined for those. Let me know if you need more. 

https://www.figma.com/file/y6Ca8BdJtQEd3Of1saRieF/branch/6MR4jvUO9jG5pKEogHszHR/DS%3A-Web-Components?node-id=4284%3A5154

**Comment by WilliamKelley** [comment]
Awesome, looks great. A `:focus` styling would be required as well

**Comment by WilliamKelley** [comment]
@alecdanz bump

**Comment by alecdanz** [comment]
Thanks for the bump, just added focus into the states.

**Comment by alecdanz** [comment]
This focus is something that we've normalized for all new components by the way.
