### ISSUE TITLE
Banner, SectionMessage, unclear action component

### ISSUE THREAD

**Issue by WilliamKelley** [prenda-school/design-system#259]
### Design Feedback

Both Banner and SectionMessage have an "action" slot where a "Close" icon and "Details <ArrowRight>" text/icon reside. In implementation, these would be an IconButton and Button, respectively. The designs should also use those components.

Anticipating your initial thoughts, the IconButton "text" variant would be used, but its icon color would have to change. Specifically, we set it to "inherit" from the parent component (e.g. Banner) in the initial implementation. Still, the active/focus styling may look out of place and like any context but a white background wasn't considered in the "text" variant Buttons' designs.

To this end, I believe the solution is either
- modify "text" variant styling to be more appropriate to different background colors
- design a custom (Icon)Button variant, scoped to these components, similar to how Tag was implemented.

**Comment by WilliamKelley** [comment]
cc: @ssbittle @alecdanz

**Comment by seigler** [comment]
I think the root of this complexity is that our button design can have a potentially dark background when unfocused, and a definitely light background when focused. The banner elements won't be the first place this problem occurs; might it be better to address this in Button or IconButton?
