### ISSUE TITLE
Tag changes

### ISSUE THREAD

**Issue by alecdanz** [prenda-school/design-system#310]
**Design Changes**
- Renamed the tag to "Chip" to be closer to the material component name. 
- Updated the padding around this component to make it more "pill" shaped
- Added a small variant of this component 

[Figma Reference](https://www.figma.com/file/y6Ca8BdJtQEd3Of1saRieF/DS%3A-Web-Components?node-id=949%3A467)

**Comment by WilliamKelley** [comment]
Closed by #396
