### ISSUE TITLE
Spark Icon

### ISSUE THREAD

**Issue by DapperFox** [prenda-school/design-system#316]
Currently we have a `SparkMonogram` icon, but no Spark Symbol by itself. Some of our links for the marketing page need this as an icon to match styles of marketing page. I propose we add the Spark Symbol to the design system.

![image](https://user-images.githubusercontent.com/2700294/138970846-c3afd791-24d2-4b1d-9c65-bf4d403f2ca8.png)

**Comment by WilliamKelley** [comment]
Closed by #317
