### ISSUE TITLE
Updated palette

### ISSUE THREAD

**Issue by alecdanz** [prenda-school/design-system#322]
## Color changes

We are updating the Prenda secondary colors and adding range to the color system to support illustration work and to have colors that identify with the Prenda brand more effectively. 

These changes are a part of a bigger effort to control/stabilize the brand. 

[Figma documentation](https://www.figma.com/file/w9lodWeivyS4GHdBNIYaJr/DS%3A-Foundations?node-id=1%3A2
)

**Comment by WilliamKelley** [comment]
With these changes we've lost prescriptions for the color that text can take on. I see it's described under "Functional palette" as N600, but what about text appearing on dark backgrounds? Is that completely out of the spec now?

To this end, I think we should create a mapping. I am reversing my original assessment that it wasn't necessary. We won't use the mapping to update components, but we do need it to advise migrating independent consumer use of the v1 colors, and to migrate concepts like "dark text on light background", "light text on dark background", etc. The mapping would ideally show whether these concepts are still valid, what their new equivalents are, or whether they map to nothing and should be done away with.
