### ISSUE TITLE
Typography changes

### ISSUE THREAD

**Issue by alecdanz** [prenda-school/design-system#323]
## Typography changes

We are updating and simplifying the typography inside the Prenda design system. Big changes include no longer supporting Nunito as a Prenda font, and the introduction of **Poppins** as the new Prenda brand font. **Inter** will also be implemented as a functional product font, ensuring accessibility best practices throughout Prenda interfaces. A third font specifically for children is designated (KG neatly printed) but there are still questions over the licensing of this font before it should be implemented. 

It should be noted that this is a part of a larger brand stabilization effort. 

[Figma documentation](https://www.figma.com/file/w9lodWeivyS4GHdBNIYaJr/DS%3A-Foundations?node-id=2182%3A1320)

**Comment by WilliamKelley** [comment]
Completed by #366
