### ISSUE TITLE
Adapt styles based on props, instead of custom classes capture

### ISSUE THREAD

**Issue by WilliamKelley** [prenda-school/design-system#365]
When implementing custom variants or other prop values that need a class name, we have to do a pretty complicated capturing of classes, verbose class name determination, etc.

I propose that we bite the bullet on [adapting styles to props](https://v4.mui.com/styles/basics/#adapting-based-on-props). I avoided this because of runtime performance concerns and because v5 did not seem like it was moving it that direction at the time, however v5 _fully_ embraces this as the only option.

It makes our jobs easier as we can get rid of some boilerplate, and our consumers won't have to deal with ugly css class specificity workarounds (i.e. `'&&&'`) to override our overlapping determinations.

I'll pioneer this with my work on Unstable_Typography.

**Comment by shadoath** [comment]
I'll keep an eye on what you do for the Typography work and follow that.
