### ISSUE TITLE
Rename Topbar button design spec to Top bar

### ISSUE THREAD

**Issue by WilliamKelley** [prenda-school/design-system#511]

**Comment by alecdanz** [comment]
@WilliamKelley we already have a Topbar - I'm curious the thinking with this request for change.

**Comment by WilliamKelley** [comment]
@alecdanz Just adding the space between "Top" and "bar". The rest of the components follow a pattern of putting a space between each word.

**Comment by alecdanz** [comment]
Got it, updated! For some reason I had it in my head that that was a single word.
