### ISSUE TITLE
Unstable_Button appearing as disabled after toggling disabled on and off

### ISSUE THREAD

**Issue by slingner** [prenda-school/design-system#538]
I noticed on Storybook that when the disabled button is toggled from false to true it works correctly, but when toggled back to false, the background color does not get reset:

https://www.loom.com/share/b23849ccd1bb43b4afc0121b3c2dac90

I also noticed this when trying to conditionally toggle disabled on a PW button using a typed code("chuck"):

https://www.loom.com/share/3b90e68fd9b548688ded41adcefb6c97

@WilliamKelley Would be great if you could confirm this bug on your end, could be a fun one for us to pair on?

**Comment by WilliamKelley** [comment]
Hm, thats unfortunate. I think I came across that behavior once too. Yes we can definitely pair on it. We probably have to abandon dynamic class names for Mui v4, i'm noticing other issues too.
